# Site settings
title: 'Paschall Davis Resume'
description: "A resume written in Jekyll using joelglovier's resume template"

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar: 'true'
resume_name: 'Paschall Davis'
resume_title: 'Software Engineer'

# used for the contact button in _layouts/resume.html
resume_contact_email: 'j.paschall.davis@gmail.com'

# the next two items are used for schema itemprops in _layouts/resume.html
resume_contact_telephone: '615-618-4874'

resume_header_contact_info: '615-618-4874 • lisasimpson@youremailaddress.com'
display_header_contact_info: 'false'

resume_header_intro: "<p>As an engineer with a proven record of technical skills, strong principles, leadership, and team focus through my seven years working in technology, I'm searching for roles where I can collaborate with highly motivated like-minded developers as we strive to continue learning and deliver excellent software. I thrive in environments with enough structure to provide stability, while still having enough flexibility for occasional explorations into optimizations and new technology.</p>"

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
resume_looking_for_work: 'yes'

# Decide which sections to use
# comment out to hide
resume_section_experience: true
resume_section_education: true
resume_section_projects: false
resume_section_skills: true
resume_section_recognition: false
resume_section_links: false
resume_section_associations: false
resume_section_interests: true

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  resume_github_url: 'https://github.com/pasquatch913'
  resume_linkedin_url: 'https://www.linkedin.com/in/paschall-davis/'
  resume_website_url: 'https://pasquatch913.github.io/personal/'
resume_print_social_links: true

# Design settings
resume_theme: default
# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts
